name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  bundle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      - name: Prepare Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
        with:
          key: release
      - name: Additional tools
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Bundle plugin files
        run: just bundle
      - name: Zip files
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: colorconverter-windows-${{ github.event.workflow_run.head_branch }}.zip
          directory: bundle
          path: .
      - name: Generate zip checksum
        run: Get-FileHash -Path "bundle/colorconverter-windows-${{ github.event.workflow_run.head_branch }}.zip" -Algorithm SHA256 | Select-Object -ExpandProperty Hash > "checksum.txt"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.workflow_run.head_branch }}-windows-artifact
          path: bundle/colorconverter-windows-${{ github.event.workflow_run.head_branch }}.zip
          if-no-files-found: error
      - name: Upload artifact checksum
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.workflow_run.head_branch }}-windows-artifact-checksum
          path: checksum.txt
          if-no-files-found: error
  release:
    if: ${{ startsWith(github.event.workflow_run.head_branch, 'v') }}
    runs-on: windows-latest
    needs: bundle
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true
      - name: Create release ${{ github.event.workflow_run.head_branch }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/colorconverter-windows-${{ github.event.workflow_run.head_branch }}.zip,release/checksum.txt"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.workflow_run.head_branch }}
          artifactErrorsFailBuild: true
